# Dependencies
markdown:         redcarpet
rouge:         true

# Permalinks
permalink:        pretty

# Setup
title:            Marcelo Tozzi
tagline:          'Blog'
description:      'Blog pessoal'
url:              http://www.marcelotozzi.com
baseurl:          '/'
paginate:         5

author:
  name:           'Marcelo Tozzi'
  url:            https://twitter.com/marcelotozzi

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/marcelotozzi/marcelotozzi.github.io
